spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432
    username: job
    password: job

  flyway:
    url: jdbc:postgresql://localhost:5432/job
    user: job
    password: job

server:
  port: 8081
