services:
  # Postgres
  postgres:
    image: bitnami/postgresql:16.1.0
    ports:
      - 5432:5432
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_data:/bitnami/postgresql
      - ./config/postgres:/docker-entrypoint-initdb.d

  # NATS
  nats:
    image: bitnami/nats:2.10.5
    ports:
      - 4222:4222
      - 8222:8222

  # Neo4j
  neo4j:
    image: neo4j
    environment:
      NEO4J_PLUGINS: "[\"apoc\", \"apoc-extended\"]"
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_security_procedures_allowlist: gds.*, apoc.*
      NEO4J_dbms_security_procedures_unrestricted: gds.*, apoc.*
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - neo4j_data:/bitnami/neo4j
      - ./backend/recommendation/apoc.conf:/var/lib/neo4j/conf/apoc.conf
      - ./backend/recommendation/schema.cypher:/var/lib/neo4j/db_init/schema.cypher

volumes:
  postgresql_data:
  neo4j_data:
