apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkedout-messaging
  labels:
    app.kubernetes.io/name: linkedout-messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: linkedout-messaging
  template:
    metadata:
      labels:
        app.kubernetes.io/name: linkedout-messaging
        app.kubernetes.io/part-of: linkedout
    spec:
      containers:
      - name: linkedout-messaging
        image: ghcr.io/thomas-mauran/linkedout/messaging
        imagePullPolicy: Always
        env: []
        ports:
          - containerPort: 8082
            name: api
