apiVersion: v1
kind: Service
metadata:
  name: linkedout-messaging
spec:
  selector:
    app.kubernetes.io/name: linkedout-messaging
  ports:
    - protocol: TCP
      port: 9090
      targetPort: api
