- op: add
  path: /metadata/annotations/cert-manager.io~1cluster-issuer
  value: letsencrypt-prod
- op: replace
  path: /spec/rules/0/host
  value: linkedout.cluster-2020-5.dopolytech.fr
- op: add
  path: /spec/tls
  value:
    - hosts:
      - linkedout.cluster-2020-5.dopolytech.fr
      secretName: linkedout.cluster-2020-5.dopolytech.fr-tls
