spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432
    username: profile
    password: profile

  flyway:
    url: jdbc:postgresql://localhost:5432/profile
    user: profile
    password: profile

server:
  port: 8085

s3:
  endpoint: https://s3-api.linkedout.cluster-2020-5.dopolytech.fr/
  bucket: linkedout
