apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkedout-employer
  labels:
    app.kubernetes.io/name: linkedout-employer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: linkedout-employer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: linkedout-employer
        app.kubernetes.io/part-of: linkedout
    spec:
      containers:
      - name: linkedout-employer
        image: ghcr.io/thomas-mauran/linkedout/employer
        imagePullPolicy: Always
        env: []
        ports:
          - containerPort: 8083
            name: api
