spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.linkedout.cluster-2020-5.dopolytech.fr/realms/linkedout-dev

server:
  port: 9090

nats:
  timeout: 1000
  spring:
    server: nats://localhost:4222

app:
  services:
    jobs:
      subjects:
        findAll: jobs.findAll
        findOne: jobs.findOne
    jobOffers:
      subjects:
        findAll: jobs.findAllJobOffers
        findOne: jobs.findOneJobOffer
    jobCategories:
      subjects:
        findAll: jobs.findAllCategories
    companies:
      subjects:
        findAll: jobs.findAllCompanies
        findOne: jobs.findOneCompany
    messageChannels:
      subjects:
        findAllOfUser: messaging.findAllChannelsOfUser
        findOneOfUser: messaging.findOneChannelOfUser
        findOneOfUserWithEmployer: messaging.findOneChannelOfUserWithEmployer
    messages:
      subjects:
        findAllOfUserInChannel: messaging.findAllMessagesOfUserInChannel
        sendMessage: messaging.sendMessage
        sendMessageToEmployer: messaging.sendMessageToEmployer
    employer:
      subjects:
        findOne: employer.findOne
        findMultiple: employer.findMultiple
    notifications:
      subjects:
        sendTo: notifications.sendTo
