spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.linkedout.cluster-2020-5.dopolytech.fr/realms/linkedout-dev

server:
  port: 9090

nats:
  timeout: 1000
  spring:
    server: nats://localhost:4222

app:
  services:
    recommendation:
      subjects:
        findAll: recommendations.findAll
    jobs:
      subjects:
        findAll: jobs.findAll
        findMultiple: jobs.findMultiple
        findOne: jobs.findOne
    jobOffers:
      subjects:
        findAllForUser: jobs.findAllJobOffersForUser
        findOneForUser: jobs.findOneJobOfferForUser
        applyTo: jobs.applyToJobOffer
    jobCategories:
      subjects:
        findAll: jobs.findAllCategories
        findMultiple: jobs.findMultipleCategories
        findOne: jobs.findOneCategory
    companies:
      subjects:
        findAll: jobs.findAllCompanies
        findMultiple: jobs.findMultipleCompanies
        findOne: jobs.findOneCompany
        ensureExists: jobs.ensureCompanyExists
    messageChannels:
      subjects:
        findAllOfUser: messaging.findAllChannelsOfUser
        findOneOfUser: messaging.findOneChannelOfUser
        findOneOfUserWithEmployer: messaging.findOneChannelOfUserWithEmployer
    messages:
      subjects:
        findAllOfUserInChannel: messaging.findAllMessagesOfUserInChannel
        sendMessage: messaging.sendMessage
        sendMessageToEmployer: messaging.sendMessageToEmployer
    employer:
      subjects:
        findOne: employer.findOne
        findMultiple: employer.findMultiple
        createEvaluation: employer.createEvaluation
        deleteEvaluation: employer.deleteEvaluation
        findOneEvaluation: employer.findOneEvaluation
    notifications:
      subjects:
        sendTo: notifications.sendTo
        findAllOfUser: notifications.findAllOfUser
        deleteAllOfUser: notifications.deleteAllOfUser
    profile:
      subjects:
        deleteOne: profile.deleteOne
        findOneOfUser: profile.findOneOfUser
        findAllRequestingDeletion: profile.findAllRequestingDeletion
        requestDeletionOfUser: profile.requestProfileDeletionOfUser
        saveOneOfUser: profile.saveOneOfUser
        updateOneOfUser: profile.updateOneOfUser
        findOneCvOfUser: profile.findOneCvOfUser
        saveOneCvOfUser: profile.saveOneCvOfUser
        findOneProfilePictureOfUser: profile.findOneProfilePictureOfUser
        saveOneProfilePictureOfUser: profile.saveOneProfilePictureOfUser
    availability:
      subjects:
        createOneOfUser: availability.createOneOfUser
        deleteOneOfUser: availability.deleteOneOfUser
        findAllOfUser: availability.findAllOfUser
        findOneOfUser: availability.findOneOfUser
        updateOneOfUser: availability.updateOneOfUser
    reference:
      subjects:
        createOneOfUser: reference.createOneOfUser
        deleteOneOfUser: reference.deleteOneOfUser
        findAllOfUser: reference.findAllOfUser
        findOneOfUser: reference.findOneOfUser
        updateOneOfUser: reference.updateOneOfUser
    experience:
      subjects:
        createOneOfUser: experience.createOneOfUser
        deleteOneOfUser: experience.deleteOneOfUser
        findAllOfUser: experience.findAllOfUser
        findOneOfUser: experience.findOneOfUser
        updateOneOfUser: experience.updateOneOfUser
    evaluation:
      subjects:
        findAllOfUser: evaluation.findAllOfUser
        findOneOfUser: evaluation.findOneOfUser
