spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/linkedout

server:
  port: 9090

nats:
  timeout: 1000
  spring:
    server: nats://localhost:4222

app:
  services:
    jobs:
      subjects:
        findAll: jobs.findAll
