name: Lint backend

on:
  workflow_call:
    inputs:
      gradle-root-project-path:
        description: The path to the Gradle root project
        default: ./backend
        required: false
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.gradle-root-project-path }}
    steps:
    - uses: actions/checkout@v4

    - name: Use Java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: corretto

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Lint Kotlin
      run: ./gradlew lintKotlin

    - name: Execute Gradle build
      run: ./gradlew build -x test
