name: Lint frontend

on:
  workflow_call:
    inputs:
      app-dir-path:
        description: The directory where the frontend application is stored
        default: ./front
        required: false
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.app-dir-path }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: ${{ inputs.app-dir-path }}

      - name: Install dependencies
        run: npm ci

      - uses: snyk/actions/node@0.4.0
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=front/package.json

      - name: Run Prettier
        run: npm run prettier:check

      - name: Run ESLint
        run: npm run eslint:check

      - name: Run TypeScript
        run: npm run typescript:check
