name: Push a semver tag

on:
  push:
    tags:
      - v*.*.*

jobs:
  build_push_backend:
    name: Build & push Docker image of the "${{ matrix.service }}" service
    uses: ./.github/workflows/flow_backend_build_push.yml
    secrets: inherit
    strategy:
      matrix:
        service: [api_gateway, jobs, messaging, employer, notification, profile, recommendation]
    with:
      service-name: ${{ matrix.service }}
      push-image: ${{ github.event_name != 'pull_request' }}
      image-tags: |
        type=sha
        type=semver,pattern={{version}}
        type=raw,value=latest
